spring.application.name=ecommerce
server.port=8080

# Configuracao do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=lucasleite
spring.datasource.password=123@lucas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracao JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Execucao do import.sql para carga inicial dos dados
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Nivel de log
logging.level.org.springframework.web=INFO
logging.level.br.edu.unifio.ecommerce=DEBUG
